### PR TITLE
Add sequential.interpolate

### PR DESCRIPTION
**Pull request by curran**
This fixes https://github.com/d3/d3-scale/issues/67

 * [x] Add failing test
 * [x] Add implementation that makes the test pass
 * [x] Update documentation

### CODE REVIEW

**Comment by mbostock** [comment]
The test implies that the *interpolate* argument to [d3.scaleSequential](https://github.com/d3/d3-scale#scaleSequential) is now optional. I think that argument should still be mandatory… unless you want it to default to `function identity(t) { return t; }`…

**Comment by mbostock** [comment]
Also *continuous*.interpolate is not the same as *sequential*.interpolate: *continuous*.interpolate takes an interpolator factory (such as d3.interpolateRgb) that is later used to construct an interpolator for each adjacent pair of elements in the range, whereas *sequential*.interpolate takes an interpolator (such as d3.interpolateRgb("red", "blue")).

Maybe it’s worth changing the name to avoid this confusion? Like, *sequential*.interpolator rather than *sequential*.interpolate.

**Comment by mbostock** [comment]
Agreeing with myself from an hour ago, I think renaming *interpolate* to *interpolator* in this context is a good idea. I already use the name “interpolator” in d3-interpolate, besides.

**Comment by mbostock** [comment]
Great! I added a couple more tests and merged.

**Comment by curran** [comment]
Awesome!

**Pull request merged**
